# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6ce58e805449894d194bd73292ec23696ca33ccd40b46b4cdaa113b36a7c846f09809b91d5bd80d84d0471c3f0b1f3c2e298a01c40e47be9387b5dd35613990

test:
  secret_key_base: de59dbb3692a3abeb9fd8b14af0f92fa8709617308ab4e3e7942abe82323f52da8c9d720b1c47401d9b0fcca57ccd2abd648ffc3a03fbc75736b0253536e6408

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
